// Generates supabase/seed.sql from the bundled sample data so DB and preview start identical.
// Run: npx esbuild scripts/gen-seed.ts --bundle --platform=node --outfile=/tmp/seed.cjs && node /tmp/seed.cjs
import { writeFileSync } from "node:fs";
import { availability, locations, stops, tattoos } from "../src/lib/data/sample";

const q = (v: unknown): string =>
  v === null || v === undefined ? "null"
  : typeof v === "number" || typeof v === "boolean" ? String(v)
  : Array.isArray(v) ? `array[${v.map(q).join(",")}]::text[]`
  : `'${String(v).replace(/'/g, "''")}'`;

const out: string[] = ["-- Generated by scripts/gen-seed.ts — sample data. Schedule rows are PLACEHOLDERS.", "begin;"];
out.push("insert into categories (slug,label,sort) values ('black-grey','Black & Grey',1),('blackwork','Blackwork',2),('gothic','Gothic',3),('american-traditional','American Traditional',4),('lettering','Lettering',5),('linework','Linework',6),('custom','Custom',7) on conflict do nothing;");
for (const t of tattoos)
  out.push(`insert into tattoos (slug,title,description,alt_text,styles,placement,featured,sort_order,image_path,image_width,image_height,image_blur,image_tone) values (${[t.slug, t.title, t.description, t.alt, t.styles, t.placement, t.featured, t.order, t.image.src, t.image.width, t.image.height, t.image.blur, t.image.tone].map(q).join(",")}) on conflict (slug) do nothing;`);
for (const l of locations)
  out.push(`insert into locations (id,city,region,country,latitude,longitude,is_home) values (${[l.id, l.city, l.region, l.country, l.latitude, l.longitude, !!l.isHome].map(q).join(",")}) on conflict do nothing;`);
for (const s of stops)
  out.push(`insert into schedule (id,location_id,kind,venue,start_date,end_date,status,appointment_windows,spots_remaining,note,is_placeholder) values (${[s.id, s.locationId, s.kind, s.venue, s.startDate, s.endDate, s.status, s.appointmentWindows, s.spotsRemaining, s.note, s.isPlaceholder].map(q).join(",")}) on conflict do nothing;`);
for (const d of availability)
  out.push(`insert into availability (schedule_id,location_id,date,status) values (${[d.stopId, d.locationId, d.date, d.status].map(q).join(",")}) on conflict do nothing;`);
out.push("commit;");
writeFileSync("supabase/seed.sql", out.join("\n") + "\n");
console.log(`seed.sql: ${out.length} lines`);
